### ISSUE TITLE
Pare down JS includes

### ISSUE THREAD

**Issue by allanjamesvestal** [datahub/grappelli-nested-inlines#3]
(Note to self:) Do I need to be including all the Grappelli JS files in `/static`?

**Comment by sehmaschine** [comment]
I don't think you have to – just reference the original ones and include any custom js with your static folder. That said, there might be issues with collectstatic when you (for example) include inline.js and the same js is already being collected with grappelli – using a different name for that js probably solves that issue. If you have any questions concerning the integration with grappelli, do not hesitate to ask.

**Comment by allanjamesvestal** [comment]
_OH_. I remember why I did things this way.

Turns out when there are multiple inlines at the same level (or some trigger condition I always seem to hit) Grappelli's jquery.grp_inlines.js file binds click events twice.

Which is a problem, because on the inline delete that toggles the checkbox on and then off again on the same click — effectively making inline deletes impossible.

My solution to this was to be more specific in my selectors: each element with `.grp-delete-handler` also gets a class that's the same as the inline's topmost ID (just to have something that'll definitely be unique on the page).

You can see the code here: https://github.com/datahub/grappelli-nested-inlines/blob/master/grappelli_nested/static/grappelli/js/jquery.grp_inline.js (versus the original at https://github.com/sehmaschine/django-grappelli/blob/master/grappelli/static/grappelli/js/jquery.grp_inline.js).

I was originally hoping my 'static/grappelli' folder would just override that file from my Grappelli install. But there are a couple of better ways to do this:
- Making a pull request to Grappelli that would merge my changes to jquery.grp_inline.js into the core version of the files (which would be future-proof, if a tiny bit crufty for non-inline-users), or
- Putting this in a separate 'static/grappelli_nested' folder and importing it after jquery.grp_inline.js to directly override that file for inline users.

@sehmaschine, which would you prefer? Not sure if there are other use cases that would benefit from making handlers unique. Definitely want to check in with you before I change things either way.

**Comment by sehmaschine** [comment]
a) click events should not be triggered twice. if that's the case, it's a bug (though I'm not able to reproduce it).
b) the link to your jquery.grp_inline.js doesn't work.

about the handlers: I'm definitely +1 on solving the bug with multiple click events. I've opened a ticket (https://github.com/sehmaschine/django-grappelli/issues/506) and I'll try to do some research asap. not sure what's the best solution right now.

**Comment by sehmaschine** [comment]
I've check the issue and I'm not able to reproduce the multiple click events. Can you add more details?
